### ISSUE TITLE
breezedecoration.cpp:1318:13: error: 'setBlurRegion' was not declared in this scope

### ISSUE THREAD

**Issue by xyve7** [paulmcauley/classik#23]
I was installing Classik from source and ran into this error:

![image](https://user-images.githubusercontent.com/60116559/166616733-95be4040-bfb2-47cb-ac33-d911e156e58d.png)

**Comment by paulmcauley** [comment]
See: https://github.com/paulmcauley/classik/issues/19

This is caused by commit fe48c052f529e889706214c9af3db200fbfdb2a8 . This is in preparation for Plasma 5.25 when setBlurRegion will be available (It is currently only available on 5.24.80 unstable releases of Plasma). I decided to put it on master as the Plasma 5.25 release will only be a month away.

If in the meantime you want to run code from the master branch,  use it from before that commit or that tagged as a previous official release. E.g.: https://github.com/paulmcauley/classik/tree/3.0.breeze5.23.80

**Comment by Yasand123** [comment]
I still get this error even tho I have 5.25, on Arch.
